repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.269'
  hooks:
    - id: ruff
      args: ["--select", "E,F,I", "--fix"]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    args: [--config=./pyproject.toml]