repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    args: [--config=./pyproject.toml]

