FROM python:3.8-slim

# Set the working directory within the container
WORKDIR /app

COPY . /app

RUN pip install -r /app/dashboard/requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "/app/dashboard/main.py"]