[tool.poetry.dependencies]
python = "3.8"
streamlit = "*"
requests = "*"
yfinance = "*"
dask = "*"
numpy = "*"
plotly = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
